chore: remove was_forced from CreatePatchRequest
shorebirdtech/shorebird pull request #2370
Opened 2024-07-19 21:25 UTC by bryanoltman

## Description

We haven't supported the `--force` flag in our patch command for quite a while, so this is no longer a useful field.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore
- [ ] 🧪 Tests

2024-07-19 21:27 UTC, eseidel approved these changes

2024-07-20 02:31 UTC, felangel requested changes
Won’t we need to bump the code push client version since this is a breaking change in the protocol?

2024-07-22 20:11 UTC, bryanoltman commented
> Won’t we need to bump the code push client version since this is a breaking change in the protocol?

We can, but it's not necessary. With https://github.com/shorebirdtech/_shorebird/pull/737, we no longer read this field.

2024-07-23 20:57 UTC, felangel approved these changes

2024-07-23 21:00 UTC, merged