Add a channel command
shorebirdtech/shorebird pull request #638
Opened 2023-06-12 21:27 UTC by sladyn98

## Description

This PR would add support for a channel command that uses git branches as channels.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-06-13 14:44 UTC, felangel commented on packages/shorebird_cli/lib/src/commands/channel_command.dart
> +      print('Please provide a branch name to switch to.');
We should use the `logger` instead of `print`

2023-06-13 14:44 UTC, felangel commented on packages/shorebird_cli/lib/src/commands/channel_command.dart
> +    final result = await Process.run('git', ['checkout', branch]);
We should use `ShorebirdProcess` instead of `Process`

2023-06-13 14:45 UTC, felangel commented on packages/shorebird_cli/lib/src/commands/channel_command.dart
> +class ChannelCommand extends Command {
We'll need to add tests for the command in order for this to be mergable.

2023-06-13 14:45 UTC, felangel commented on packages/shorebird_cli/lib/src/commands/channel_command.dart
> +import 'package:args/command_runner.dart';
```suggestion
import 'package:args/args.dart';
```

2023-06-13 14:45 UTC, felangel commented on packages/shorebird_cli/lib/src/commands/commands.dart
> +export 'channel_command.dart';
We'll also need to add the new command to the `CommandRunner` in order for it to be usable.

2023-06-13 14:46 UTC, felangel requested changes
Thanks for the PR! I left a few comments but I also am not sure this is needed at the moment since we release quite frequently. We'll discuss a bit more an let you know but either way we really appreciate you taking the time to contribute! 💙

2023-10-17 19:34 UTC, bryanoltman commented
This seems abandoned and doesn't have any tests. Going to close, please reopen if you're still interested in landing.

2023-10-17 19:34 UTC, closed without merging